-- Update training_scenarios table for multi-product platform support
-- Adds product relationship and auto-generation tracking

-- Add product_id to link scenarios to specific products
ALTER TABLE training_scenarios
ADD COLUMN IF NOT EXISTS product_id UUID REFERENCES product_profiles(id) ON DELETE SET NULL;

-- Add auto_generated flag to track AI-generated vs manually created scenarios
ALTER TABLE training_scenarios
ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT false;

-- Add knowledge_base_refs to store references to relevant knowledge base entries
-- This helps AI know which documents to use when generating responses
ALTER TABLE training_scenarios
ADD COLUMN IF NOT EXISTS knowledge_base_refs JSONB DEFAULT '[]'::jsonb;

-- Add generation_prompt to store the prompt used to generate the scenario (for AI-generated ones)
ALTER TABLE training_scenarios
ADD COLUMN IF NOT EXISTS generation_prompt TEXT;

-- Add generation_metadata for storing additional info about how scenario was created
ALTER TABLE training_scenarios
ADD COLUMN IF NOT EXISTS generation_metadata JSONB DEFAULT '{}'::jsonb;

-- Create index on product_id for efficient filtering
CREATE INDEX IF NOT EXISTS idx_training_scenarios_product ON training_scenarios(product_id);

-- Create index on auto_generated for filtering
CREATE INDEX IF NOT EXISTS idx_training_scenarios_auto_generated ON training_scenarios(auto_generated);

-- Update RLS policies to include product-based filtering

-- Drop existing policies if they conflict (optional - only if needed)
-- DROP POLICY IF EXISTS "Users can view global scenarios" ON training_scenarios;
-- DROP POLICY IF EXISTS "Users can view their scenarios" ON training_scenarios;

-- Create new policy: Users can view scenarios for active products
CREATE POLICY "Users can view scenarios for active products"
  ON training_scenarios
  FOR SELECT
  TO authenticated
  USING (
    -- Global scenarios (no product_id)
    product_id IS NULL
    OR
    -- Scenarios for active products
    EXISTS (
      SELECT 1 FROM product_profiles
      WHERE id = training_scenarios.product_id
      AND is_active = true
    )
  );

-- Add comments
COMMENT ON COLUMN training_scenarios.product_id IS 'Links scenario to a specific product (NULL for global scenarios)';
COMMENT ON COLUMN training_scenarios.auto_generated IS 'Whether this scenario was auto-generated by AI';
COMMENT ON COLUMN training_scenarios.knowledge_base_refs IS 'Array of knowledge base entry IDs relevant to this scenario';
COMMENT ON COLUMN training_scenarios.generation_prompt IS 'The prompt used to generate this scenario (for AI-generated scenarios)';
COMMENT ON COLUMN training_scenarios.generation_metadata IS 'Additional metadata about scenario generation (model, temperature, etc.)';
